### ISSUE TITLE
Опечатка в названии регистра

### ISSUE THREAD

**Issue by omega1x** [SVrz/APK-SrtaReg#1]
[Опечатка](https://github.com/SVrz/APK-SrtaReg/blame/d47ab7f1fa75d8b49b0c8b69c93ae50817d8f990/manuals/manuals.md#L43C15-L43C27) в наименовании регистра `UMIK_modbuss`

**Comment by SVrz** [comment]
Спасибо, что указали. Исправил опечатку.
